# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label_selector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='label_selector.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14label_selector.proto\x12\tfirmament\"\xd4\x01\n\rLabelSelector\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.firmament.LabelSelector.SelectorType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"q\n\x0cSelectorType\x12\n\n\x06IN_SET\x10\x00\x12\x0e\n\nNOT_IN_SET\x10\x01\x12\x0e\n\nEXISTS_KEY\x10\x02\x12\x12\n\x0eNOT_EXISTS_KEY\x10\x03\x12\x10\n\x0cGREATER_THAN\x10\x04\x12\x0f\n\x0bLESSER_THAN\x10\x05\x62\x06proto3')
)



_LABELSELECTOR_SELECTORTYPE = _descriptor.EnumDescriptor(
  name='SelectorType',
  full_name='firmament.LabelSelector.SelectorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IN_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_IN_SET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXISTS_KEY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_EXISTS_KEY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREATER_THAN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LESSER_THAN', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_LABELSELECTOR_SELECTORTYPE)


_LABELSELECTOR = _descriptor.Descriptor(
  name='LabelSelector',
  full_name='firmament.LabelSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='firmament.LabelSelector.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.LabelSelector.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='firmament.LabelSelector.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LABELSELECTOR_SELECTORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=248,
)

_LABELSELECTOR.fields_by_name['type'].enum_type = _LABELSELECTOR_SELECTORTYPE
_LABELSELECTOR_SELECTORTYPE.containing_type = _LABELSELECTOR
DESCRIPTOR.message_types_by_name['LabelSelector'] = _LABELSELECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelSelector = _reflection.GeneratedProtocolMessageType('LabelSelector', (_message.Message,), {
  'DESCRIPTOR' : _LABELSELECTOR,
  '__module__' : 'label_selector_pb2'
  # @@protoc_insertion_point(class_scope:firmament.LabelSelector)
  })
_sym_db.RegisterMessage(LabelSelector)


# @@protoc_insertion_point(module_scope)
