# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_affinity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_affinity.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13node_affinity.proto\x12\tfirmament\"H\n\x17NodeSelectorRequirement\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"P\n\x10NodeSelectorTerm\x12<\n\x10matchExpressions\x18\x01 \x03(\x0b\x32\".firmament.NodeSelectorRequirement\"F\n\x0cNodeSelector\x12\x36\n\x11nodeSelectorTerms\x18\x01 \x03(\x0b\x32\x1b.firmament.NodeSelectorTerm\"Z\n\x17PreferredSchedulingTerm\x12\x0e\n\x06weight\x18\x01 \x01(\x05\x12/\n\npreference\x18\x02 \x01(\x0b\x32\x1b.firmament.NodeSelectorTerm\"\xbc\x01\n\x0cNodeAffinity\x12O\n.requiredDuringSchedulingIgnoredDuringExecution\x18\x01 \x01(\x0b\x32\x17.firmament.NodeSelector\x12[\n/preferredDuringSchedulingIgnoredDuringExecution\x18\x02 \x03(\x0b\x32\".firmament.PreferredSchedulingTermb\x06proto3')
)




_NODESELECTORREQUIREMENT = _descriptor.Descriptor(
  name='NodeSelectorRequirement',
  full_name='firmament.NodeSelectorRequirement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.NodeSelectorRequirement.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='firmament.NodeSelectorRequirement.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='firmament.NodeSelectorRequirement.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=106,
)


_NODESELECTORTERM = _descriptor.Descriptor(
  name='NodeSelectorTerm',
  full_name='firmament.NodeSelectorTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchExpressions', full_name='firmament.NodeSelectorTerm.matchExpressions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=188,
)


_NODESELECTOR = _descriptor.Descriptor(
  name='NodeSelector',
  full_name='firmament.NodeSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeSelectorTerms', full_name='firmament.NodeSelector.nodeSelectorTerms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=260,
)


_PREFERREDSCHEDULINGTERM = _descriptor.Descriptor(
  name='PreferredSchedulingTerm',
  full_name='firmament.PreferredSchedulingTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='firmament.PreferredSchedulingTerm.weight', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preference', full_name='firmament.PreferredSchedulingTerm.preference', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=352,
)


_NODEAFFINITY = _descriptor.Descriptor(
  name='NodeAffinity',
  full_name='firmament.NodeAffinity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requiredDuringSchedulingIgnoredDuringExecution', full_name='firmament.NodeAffinity.requiredDuringSchedulingIgnoredDuringExecution', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferredDuringSchedulingIgnoredDuringExecution', full_name='firmament.NodeAffinity.preferredDuringSchedulingIgnoredDuringExecution', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=543,
)

_NODESELECTORTERM.fields_by_name['matchExpressions'].message_type = _NODESELECTORREQUIREMENT
_NODESELECTOR.fields_by_name['nodeSelectorTerms'].message_type = _NODESELECTORTERM
_PREFERREDSCHEDULINGTERM.fields_by_name['preference'].message_type = _NODESELECTORTERM
_NODEAFFINITY.fields_by_name['requiredDuringSchedulingIgnoredDuringExecution'].message_type = _NODESELECTOR
_NODEAFFINITY.fields_by_name['preferredDuringSchedulingIgnoredDuringExecution'].message_type = _PREFERREDSCHEDULINGTERM
DESCRIPTOR.message_types_by_name['NodeSelectorRequirement'] = _NODESELECTORREQUIREMENT
DESCRIPTOR.message_types_by_name['NodeSelectorTerm'] = _NODESELECTORTERM
DESCRIPTOR.message_types_by_name['NodeSelector'] = _NODESELECTOR
DESCRIPTOR.message_types_by_name['PreferredSchedulingTerm'] = _PREFERREDSCHEDULINGTERM
DESCRIPTOR.message_types_by_name['NodeAffinity'] = _NODEAFFINITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeSelectorRequirement = _reflection.GeneratedProtocolMessageType('NodeSelectorRequirement', (_message.Message,), {
  'DESCRIPTOR' : _NODESELECTORREQUIREMENT,
  '__module__' : 'node_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.NodeSelectorRequirement)
  })
_sym_db.RegisterMessage(NodeSelectorRequirement)

NodeSelectorTerm = _reflection.GeneratedProtocolMessageType('NodeSelectorTerm', (_message.Message,), {
  'DESCRIPTOR' : _NODESELECTORTERM,
  '__module__' : 'node_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.NodeSelectorTerm)
  })
_sym_db.RegisterMessage(NodeSelectorTerm)

NodeSelector = _reflection.GeneratedProtocolMessageType('NodeSelector', (_message.Message,), {
  'DESCRIPTOR' : _NODESELECTOR,
  '__module__' : 'node_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.NodeSelector)
  })
_sym_db.RegisterMessage(NodeSelector)

PreferredSchedulingTerm = _reflection.GeneratedProtocolMessageType('PreferredSchedulingTerm', (_message.Message,), {
  'DESCRIPTOR' : _PREFERREDSCHEDULINGTERM,
  '__module__' : 'node_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PreferredSchedulingTerm)
  })
_sym_db.RegisterMessage(PreferredSchedulingTerm)

NodeAffinity = _reflection.GeneratedProtocolMessageType('NodeAffinity', (_message.Message,), {
  'DESCRIPTOR' : _NODEAFFINITY,
  '__module__' : 'node_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.NodeAffinity)
  })
_sym_db.RegisterMessage(NodeAffinity)


# @@protoc_insertion_point(module_scope)
