# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resource_stats.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14resource_stats.proto\x12\tfirmament\"\xf8\x01\n\rResourceStats\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\'\n\ncpus_stats\x18\x03 \x03(\x0b\x32\x13.firmament.CpuStats\x12\x17\n\x0fmem_allocatable\x18\x04 \x01(\x03\x12\x14\n\x0cmem_capacity\x18\x05 \x01(\x03\x12\x17\n\x0fmem_reservation\x18\x06 \x01(\x01\x12\x17\n\x0fmem_utilization\x18\x07 \x01(\x01\x12\x0f\n\x07\x64isk_bw\x18\x08 \x01(\x03\x12\x11\n\tnet_rx_bw\x18\t \x01(\x03\x12\x11\n\tnet_tx_bw\x18\n \x01(\x03\"k\n\x08\x43puStats\x12\x17\n\x0f\x63pu_allocatable\x18\x01 \x01(\x03\x12\x14\n\x0c\x63pu_capacity\x18\x02 \x01(\x03\x12\x17\n\x0f\x63pu_reservation\x18\x03 \x01(\x01\x12\x17\n\x0f\x63pu_utilization\x18\x04 \x01(\x01\x62\x06proto3')
)




_RESOURCESTATS = _descriptor.Descriptor(
  name='ResourceStats',
  full_name='firmament.ResourceStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='firmament.ResourceStats.resource_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='firmament.ResourceStats.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpus_stats', full_name='firmament.ResourceStats.cpus_stats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_allocatable', full_name='firmament.ResourceStats.mem_allocatable', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_capacity', full_name='firmament.ResourceStats.mem_capacity', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_reservation', full_name='firmament.ResourceStats.mem_reservation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_utilization', full_name='firmament.ResourceStats.mem_utilization', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_bw', full_name='firmament.ResourceStats.disk_bw', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_rx_bw', full_name='firmament.ResourceStats.net_rx_bw', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_tx_bw', full_name='firmament.ResourceStats.net_tx_bw', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=284,
)


_CPUSTATS = _descriptor.Descriptor(
  name='CpuStats',
  full_name='firmament.CpuStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_allocatable', full_name='firmament.CpuStats.cpu_allocatable', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_capacity', full_name='firmament.CpuStats.cpu_capacity', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_reservation', full_name='firmament.CpuStats.cpu_reservation', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_utilization', full_name='firmament.CpuStats.cpu_utilization', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=393,
)

_RESOURCESTATS.fields_by_name['cpus_stats'].message_type = _CPUSTATS
DESCRIPTOR.message_types_by_name['ResourceStats'] = _RESOURCESTATS
DESCRIPTOR.message_types_by_name['CpuStats'] = _CPUSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceStats = _reflection.GeneratedProtocolMessageType('ResourceStats', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCESTATS,
  '__module__' : 'resource_stats_pb2'
  # @@protoc_insertion_point(class_scope:firmament.ResourceStats)
  })
_sym_db.RegisterMessage(ResourceStats)

CpuStats = _reflection.GeneratedProtocolMessageType('CpuStats', (_message.Message,), {
  'DESCRIPTOR' : _CPUSTATS,
  '__module__' : 'resource_stats_pb2'
  # @@protoc_insertion_point(class_scope:firmament.CpuStats)
  })
_sym_db.RegisterMessage(CpuStats)


# @@protoc_insertion_point(module_scope)
