# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduling_delta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduling_delta.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16scheduling_delta.proto\x12\tfirmament\"\xa9\x01\n\x0fSchedulingDelta\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x33\n\x04type\x18\x03 \x01(\x0e\x32%.firmament.SchedulingDelta.ChangeType\";\n\nChangeType\x12\x08\n\x04NOOP\x10\x00\x12\t\n\x05PLACE\x10\x01\x12\x0b\n\x07PREEMPT\x10\x02\x12\x0b\n\x07MIGRATE\x10\x03\x62\x06proto3')
)



_SCHEDULINGDELTA_CHANGETYPE = _descriptor.EnumDescriptor(
  name='ChangeType',
  full_name='firmament.SchedulingDelta.ChangeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOOP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLACE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREEMPT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIGRATE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=148,
  serialized_end=207,
)
_sym_db.RegisterEnumDescriptor(_SCHEDULINGDELTA_CHANGETYPE)


_SCHEDULINGDELTA = _descriptor.Descriptor(
  name='SchedulingDelta',
  full_name='firmament.SchedulingDelta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='firmament.SchedulingDelta.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='firmament.SchedulingDelta.resource_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='firmament.SchedulingDelta.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCHEDULINGDELTA_CHANGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=207,
)

_SCHEDULINGDELTA.fields_by_name['type'].enum_type = _SCHEDULINGDELTA_CHANGETYPE
_SCHEDULINGDELTA_CHANGETYPE.containing_type = _SCHEDULINGDELTA
DESCRIPTOR.message_types_by_name['SchedulingDelta'] = _SCHEDULINGDELTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchedulingDelta = _reflection.GeneratedProtocolMessageType('SchedulingDelta', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULINGDELTA,
  '__module__' : 'scheduling_delta_pb2'
  # @@protoc_insertion_point(class_scope:firmament.SchedulingDelta)
  })
_sym_db.RegisterMessage(SchedulingDelta)


# @@protoc_insertion_point(module_scope)
