# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whare_map_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='whare_map_stats.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15whare_map_stats.proto\x12\tfirmament\"r\n\rWhareMapStats\x12\x10\n\x08num_idle\x18\x01 \x01(\x04\x12\x12\n\nnum_devils\x18\x02 \x01(\x04\x12\x13\n\x0bnum_rabbits\x18\x03 \x01(\x04\x12\x11\n\tnum_sheep\x18\x04 \x01(\x04\x12\x13\n\x0bnum_turtles\x18\x05 \x01(\x04\x62\x06proto3')
)




_WHAREMAPSTATS = _descriptor.Descriptor(
  name='WhareMapStats',
  full_name='firmament.WhareMapStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_idle', full_name='firmament.WhareMapStats.num_idle', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_devils', full_name='firmament.WhareMapStats.num_devils', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_rabbits', full_name='firmament.WhareMapStats.num_rabbits', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_sheep', full_name='firmament.WhareMapStats.num_sheep', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_turtles', full_name='firmament.WhareMapStats.num_turtles', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['WhareMapStats'] = _WHAREMAPSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WhareMapStats = _reflection.GeneratedProtocolMessageType('WhareMapStats', (_message.Message,), {
  'DESCRIPTOR' : _WHAREMAPSTATS,
  '__module__' : 'whare_map_stats_pb2'
  # @@protoc_insertion_point(class_scope:firmament.WhareMapStats)
  })
_sym_db.RegisterMessage(WhareMapStats)


# @@protoc_insertion_point(module_scope)
