# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: affinity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import node_affinity_pb2 as node__affinity__pb2
import pod_affinity_pb2 as pod__affinity__pb2
import pod_anti_affinity_pb2 as pod__anti__affinity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='affinity.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x61\x66\x66inity.proto\x12\tfirmament\x1a\x13node_affinity.proto\x1a\x12pod_affinity.proto\x1a\x17pod_anti_affinity.proto\"\x9f\x01\n\x08\x41\x66\x66inity\x12.\n\rnode_affinity\x18\x01 \x01(\x0b\x32\x17.firmament.NodeAffinity\x12,\n\x0cpod_affinity\x18\x02 \x01(\x0b\x32\x16.firmament.PodAffinity\x12\x35\n\x11pod_anti_affinity\x18\x03 \x01(\x0b\x32\x1a.firmament.PodAntiAffinityb\x06proto3')
  ,
  dependencies=[node__affinity__pb2.DESCRIPTOR,pod__affinity__pb2.DESCRIPTOR,pod__anti__affinity__pb2.DESCRIPTOR,])




_AFFINITY = _descriptor.Descriptor(
  name='Affinity',
  full_name='firmament.Affinity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_affinity', full_name='firmament.Affinity.node_affinity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pod_affinity', full_name='firmament.Affinity.pod_affinity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pod_anti_affinity', full_name='firmament.Affinity.pod_anti_affinity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=255,
)

_AFFINITY.fields_by_name['node_affinity'].message_type = node__affinity__pb2._NODEAFFINITY
_AFFINITY.fields_by_name['pod_affinity'].message_type = pod__affinity__pb2._PODAFFINITY
_AFFINITY.fields_by_name['pod_anti_affinity'].message_type = pod__anti__affinity__pb2._PODANTIAFFINITY
DESCRIPTOR.message_types_by_name['Affinity'] = _AFFINITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Affinity = _reflection.GeneratedProtocolMessageType('Affinity', (_message.Message,), {
  'DESCRIPTOR' : _AFFINITY,
  '__module__' : 'affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.Affinity)
  })
_sym_db.RegisterMessage(Affinity)


# @@protoc_insertion_point(module_scope)
