# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coco_interference_scores.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coco_interference_scores.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x63oco_interference_scores.proto\x12\tfirmament\"v\n\x16\x43oCoInterferenceScores\x12\x15\n\rdevil_penalty\x18\x01 \x01(\r\x12\x16\n\x0erabbit_penalty\x18\x02 \x01(\r\x12\x15\n\rsheep_penalty\x18\x03 \x01(\r\x12\x16\n\x0eturtle_penalty\x18\x04 \x01(\rb\x06proto3')
)




_COCOINTERFERENCESCORES = _descriptor.Descriptor(
  name='CoCoInterferenceScores',
  full_name='firmament.CoCoInterferenceScores',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devil_penalty', full_name='firmament.CoCoInterferenceScores.devil_penalty', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rabbit_penalty', full_name='firmament.CoCoInterferenceScores.rabbit_penalty', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sheep_penalty', full_name='firmament.CoCoInterferenceScores.sheep_penalty', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turtle_penalty', full_name='firmament.CoCoInterferenceScores.turtle_penalty', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['CoCoInterferenceScores'] = _COCOINTERFERENCESCORES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoCoInterferenceScores = _reflection.GeneratedProtocolMessageType('CoCoInterferenceScores', (_message.Message,), {
  'DESCRIPTOR' : _COCOINTERFERENCESCORES,
  '__module__' : 'coco_interference_scores_pb2'
  # @@protoc_insertion_point(class_scope:firmament.CoCoInterferenceScores)
  })
_sym_db.RegisterMessage(CoCoInterferenceScores)


# @@protoc_insertion_point(module_scope)
