# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_desc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import task_desc_pb2 as task__desc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='job_desc.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ejob_desc.proto\x12\tfirmament\x1a\x0ftask_desc.proto\"\xdf\x02\n\rJobDescriptor\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x05state\x18\x03 \x01(\x0e\x32!.firmament.JobDescriptor.JobState\x12,\n\troot_task\x18\x04 \x01(\x0b\x32\x19.firmament.TaskDescriptor\x12\x12\n\noutput_ids\x18\x05 \x03(\x0c\x12\x1b\n\x13min_number_of_tasks\x18\x06 \x01(\x04\x12\x1d\n\x15scheduled_tasks_count\x18\x07 \x01(\x04\x12\x1e\n\x16is_gang_scheduling_job\x18\x08 \x01(\x08\"b\n\x08JobState\x12\x07\n\x03NEW\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\x0b\n\x07\x41\x42ORTED\x10\x05\x12\x0b\n\x07UNKNOWN\x10\x06\x62\x06proto3')
  ,
  dependencies=[task__desc__pb2.DESCRIPTOR,])



_JOBDESCRIPTOR_JOBSTATE = _descriptor.EnumDescriptor(
  name='JobState',
  full_name='firmament.JobDescriptor.JobState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=300,
  serialized_end=398,
)
_sym_db.RegisterEnumDescriptor(_JOBDESCRIPTOR_JOBSTATE)


_JOBDESCRIPTOR = _descriptor.Descriptor(
  name='JobDescriptor',
  full_name='firmament.JobDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='firmament.JobDescriptor.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='firmament.JobDescriptor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='firmament.JobDescriptor.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root_task', full_name='firmament.JobDescriptor.root_task', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_ids', full_name='firmament.JobDescriptor.output_ids', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_number_of_tasks', full_name='firmament.JobDescriptor.min_number_of_tasks', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheduled_tasks_count', full_name='firmament.JobDescriptor.scheduled_tasks_count', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_gang_scheduling_job', full_name='firmament.JobDescriptor.is_gang_scheduling_job', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOBDESCRIPTOR_JOBSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=398,
)

_JOBDESCRIPTOR.fields_by_name['state'].enum_type = _JOBDESCRIPTOR_JOBSTATE
_JOBDESCRIPTOR.fields_by_name['root_task'].message_type = task__desc__pb2._TASKDESCRIPTOR
_JOBDESCRIPTOR_JOBSTATE.containing_type = _JOBDESCRIPTOR
DESCRIPTOR.message_types_by_name['JobDescriptor'] = _JOBDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobDescriptor = _reflection.GeneratedProtocolMessageType('JobDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _JOBDESCRIPTOR,
  '__module__' : 'job_desc_pb2'
  # @@protoc_insertion_point(class_scope:firmament.JobDescriptor)
  })
_sym_db.RegisterMessage(JobDescriptor)


# @@protoc_insertion_point(module_scope)
