# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pod_anti_affinity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pod_anti_affinity.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17pod_anti_affinity.proto\x12\tfirmament\"0\n\x12MatchLabelsAntiAff\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"P\n\x1fLabelSelectorRequirementAntiAff\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"\x90\x01\n\x14LabelSelectorAntiAff\x12\x32\n\x0bmatchLabels\x18\x01 \x01(\x0b\x32\x1d.firmament.MatchLabelsAntiAff\x12\x44\n\x10matchExpressions\x18\x02 \x03(\x0b\x32*.firmament.LabelSelectorRequirementAntiAff\"y\n\x16PodAffinityTermAntiAff\x12\x36\n\rlabelSelector\x18\x01 \x01(\x0b\x32\x1f.firmament.LabelSelectorAntiAff\x12\x12\n\nnamespaces\x18\x02 \x03(\t\x12\x13\n\x0btopologyKey\x18\x03 \x01(\t\"l\n\x1eWeightedPodAffinityTermAntiAff\x12\x0e\n\x06weight\x18\x01 \x01(\x05\x12:\n\x0fpodAffinityTerm\x18\x02 \x01(\x0b\x32!.firmament.PodAffinityTermAntiAff\"\xd0\x01\n\x0fPodAntiAffinity\x12Y\n.requiredDuringSchedulingIgnoredDuringExecution\x18\x01 \x03(\x0b\x32!.firmament.PodAffinityTermAntiAff\x12\x62\n/preferredDuringSchedulingIgnoredDuringExecution\x18\x02 \x03(\x0b\x32).firmament.WeightedPodAffinityTermAntiAffb\x06proto3')
)




_MATCHLABELSANTIAFF = _descriptor.Descriptor(
  name='MatchLabelsAntiAff',
  full_name='firmament.MatchLabelsAntiAff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.MatchLabelsAntiAff.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='firmament.MatchLabelsAntiAff.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=86,
)


_LABELSELECTORREQUIREMENTANTIAFF = _descriptor.Descriptor(
  name='LabelSelectorRequirementAntiAff',
  full_name='firmament.LabelSelectorRequirementAntiAff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.LabelSelectorRequirementAntiAff.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='firmament.LabelSelectorRequirementAntiAff.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='firmament.LabelSelectorRequirementAntiAff.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=168,
)


_LABELSELECTORANTIAFF = _descriptor.Descriptor(
  name='LabelSelectorAntiAff',
  full_name='firmament.LabelSelectorAntiAff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchLabels', full_name='firmament.LabelSelectorAntiAff.matchLabels', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matchExpressions', full_name='firmament.LabelSelectorAntiAff.matchExpressions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=315,
)


_PODAFFINITYTERMANTIAFF = _descriptor.Descriptor(
  name='PodAffinityTermAntiAff',
  full_name='firmament.PodAffinityTermAntiAff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelSelector', full_name='firmament.PodAffinityTermAntiAff.labelSelector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='firmament.PodAffinityTermAntiAff.namespaces', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topologyKey', full_name='firmament.PodAffinityTermAntiAff.topologyKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=438,
)


_WEIGHTEDPODAFFINITYTERMANTIAFF = _descriptor.Descriptor(
  name='WeightedPodAffinityTermAntiAff',
  full_name='firmament.WeightedPodAffinityTermAntiAff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='firmament.WeightedPodAffinityTermAntiAff.weight', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='podAffinityTerm', full_name='firmament.WeightedPodAffinityTermAntiAff.podAffinityTerm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=548,
)


_PODANTIAFFINITY = _descriptor.Descriptor(
  name='PodAntiAffinity',
  full_name='firmament.PodAntiAffinity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requiredDuringSchedulingIgnoredDuringExecution', full_name='firmament.PodAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferredDuringSchedulingIgnoredDuringExecution', full_name='firmament.PodAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=759,
)

_LABELSELECTORANTIAFF.fields_by_name['matchLabels'].message_type = _MATCHLABELSANTIAFF
_LABELSELECTORANTIAFF.fields_by_name['matchExpressions'].message_type = _LABELSELECTORREQUIREMENTANTIAFF
_PODAFFINITYTERMANTIAFF.fields_by_name['labelSelector'].message_type = _LABELSELECTORANTIAFF
_WEIGHTEDPODAFFINITYTERMANTIAFF.fields_by_name['podAffinityTerm'].message_type = _PODAFFINITYTERMANTIAFF
_PODANTIAFFINITY.fields_by_name['requiredDuringSchedulingIgnoredDuringExecution'].message_type = _PODAFFINITYTERMANTIAFF
_PODANTIAFFINITY.fields_by_name['preferredDuringSchedulingIgnoredDuringExecution'].message_type = _WEIGHTEDPODAFFINITYTERMANTIAFF
DESCRIPTOR.message_types_by_name['MatchLabelsAntiAff'] = _MATCHLABELSANTIAFF
DESCRIPTOR.message_types_by_name['LabelSelectorRequirementAntiAff'] = _LABELSELECTORREQUIREMENTANTIAFF
DESCRIPTOR.message_types_by_name['LabelSelectorAntiAff'] = _LABELSELECTORANTIAFF
DESCRIPTOR.message_types_by_name['PodAffinityTermAntiAff'] = _PODAFFINITYTERMANTIAFF
DESCRIPTOR.message_types_by_name['WeightedPodAffinityTermAntiAff'] = _WEIGHTEDPODAFFINITYTERMANTIAFF
DESCRIPTOR.message_types_by_name['PodAntiAffinity'] = _PODANTIAFFINITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchLabelsAntiAff = _reflection.GeneratedProtocolMessageType('MatchLabelsAntiAff', (_message.Message,), {
  'DESCRIPTOR' : _MATCHLABELSANTIAFF,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.MatchLabelsAntiAff)
  })
_sym_db.RegisterMessage(MatchLabelsAntiAff)

LabelSelectorRequirementAntiAff = _reflection.GeneratedProtocolMessageType('LabelSelectorRequirementAntiAff', (_message.Message,), {
  'DESCRIPTOR' : _LABELSELECTORREQUIREMENTANTIAFF,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.LabelSelectorRequirementAntiAff)
  })
_sym_db.RegisterMessage(LabelSelectorRequirementAntiAff)

LabelSelectorAntiAff = _reflection.GeneratedProtocolMessageType('LabelSelectorAntiAff', (_message.Message,), {
  'DESCRIPTOR' : _LABELSELECTORANTIAFF,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.LabelSelectorAntiAff)
  })
_sym_db.RegisterMessage(LabelSelectorAntiAff)

PodAffinityTermAntiAff = _reflection.GeneratedProtocolMessageType('PodAffinityTermAntiAff', (_message.Message,), {
  'DESCRIPTOR' : _PODAFFINITYTERMANTIAFF,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PodAffinityTermAntiAff)
  })
_sym_db.RegisterMessage(PodAffinityTermAntiAff)

WeightedPodAffinityTermAntiAff = _reflection.GeneratedProtocolMessageType('WeightedPodAffinityTermAntiAff', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHTEDPODAFFINITYTERMANTIAFF,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.WeightedPodAffinityTermAntiAff)
  })
_sym_db.RegisterMessage(WeightedPodAffinityTermAntiAff)

PodAntiAffinity = _reflection.GeneratedProtocolMessageType('PodAntiAffinity', (_message.Message,), {
  'DESCRIPTOR' : _PODANTIAFFINITY,
  '__module__' : 'pod_anti_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PodAntiAffinity)
  })
_sym_db.RegisterMessage(PodAntiAffinity)


# @@protoc_insertion_point(module_scope)
