# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pod_affinity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pod_affinity.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12pod_affinity.proto\x12\tfirmament\")\n\x0bMatchLabels\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"I\n\x18LabelSelectorRequirement\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08operator\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"~\n\x10PodLabelSelector\x12+\n\x0bmatchLabels\x18\x01 \x01(\x0b\x32\x16.firmament.MatchLabels\x12=\n\x10matchExpressions\x18\x02 \x03(\x0b\x32#.firmament.LabelSelectorRequirement\"n\n\x0fPodAffinityTerm\x12\x32\n\rlabelSelector\x18\x01 \x01(\x0b\x32\x1b.firmament.PodLabelSelector\x12\x12\n\nnamespaces\x18\x02 \x03(\t\x12\x13\n\x0btopologyKey\x18\x03 \x01(\t\"^\n\x17WeightedPodAffinityTerm\x12\x0e\n\x06weight\x18\x01 \x01(\x05\x12\x33\n\x0fpodAffinityTerm\x18\x02 \x01(\x0b\x32\x1a.firmament.PodAffinityTerm\"\xbe\x01\n\x0bPodAffinity\x12R\n.requiredDuringSchedulingIgnoredDuringExecution\x18\x01 \x03(\x0b\x32\x1a.firmament.PodAffinityTerm\x12[\n/preferredDuringSchedulingIgnoredDuringExecution\x18\x02 \x03(\x0b\x32\".firmament.WeightedPodAffinityTermb\x06proto3')
)




_MATCHLABELS = _descriptor.Descriptor(
  name='MatchLabels',
  full_name='firmament.MatchLabels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.MatchLabels.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='firmament.MatchLabels.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=74,
)


_LABELSELECTORREQUIREMENT = _descriptor.Descriptor(
  name='LabelSelectorRequirement',
  full_name='firmament.LabelSelectorRequirement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='firmament.LabelSelectorRequirement.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator', full_name='firmament.LabelSelectorRequirement.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='firmament.LabelSelectorRequirement.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=149,
)


_PODLABELSELECTOR = _descriptor.Descriptor(
  name='PodLabelSelector',
  full_name='firmament.PodLabelSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchLabels', full_name='firmament.PodLabelSelector.matchLabels', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matchExpressions', full_name='firmament.PodLabelSelector.matchExpressions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=277,
)


_PODAFFINITYTERM = _descriptor.Descriptor(
  name='PodAffinityTerm',
  full_name='firmament.PodAffinityTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelSelector', full_name='firmament.PodAffinityTerm.labelSelector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='firmament.PodAffinityTerm.namespaces', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topologyKey', full_name='firmament.PodAffinityTerm.topologyKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=389,
)


_WEIGHTEDPODAFFINITYTERM = _descriptor.Descriptor(
  name='WeightedPodAffinityTerm',
  full_name='firmament.WeightedPodAffinityTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='firmament.WeightedPodAffinityTerm.weight', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='podAffinityTerm', full_name='firmament.WeightedPodAffinityTerm.podAffinityTerm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=485,
)


_PODAFFINITY = _descriptor.Descriptor(
  name='PodAffinity',
  full_name='firmament.PodAffinity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requiredDuringSchedulingIgnoredDuringExecution', full_name='firmament.PodAffinity.requiredDuringSchedulingIgnoredDuringExecution', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferredDuringSchedulingIgnoredDuringExecution', full_name='firmament.PodAffinity.preferredDuringSchedulingIgnoredDuringExecution', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=678,
)

_PODLABELSELECTOR.fields_by_name['matchLabels'].message_type = _MATCHLABELS
_PODLABELSELECTOR.fields_by_name['matchExpressions'].message_type = _LABELSELECTORREQUIREMENT
_PODAFFINITYTERM.fields_by_name['labelSelector'].message_type = _PODLABELSELECTOR
_WEIGHTEDPODAFFINITYTERM.fields_by_name['podAffinityTerm'].message_type = _PODAFFINITYTERM
_PODAFFINITY.fields_by_name['requiredDuringSchedulingIgnoredDuringExecution'].message_type = _PODAFFINITYTERM
_PODAFFINITY.fields_by_name['preferredDuringSchedulingIgnoredDuringExecution'].message_type = _WEIGHTEDPODAFFINITYTERM
DESCRIPTOR.message_types_by_name['MatchLabels'] = _MATCHLABELS
DESCRIPTOR.message_types_by_name['LabelSelectorRequirement'] = _LABELSELECTORREQUIREMENT
DESCRIPTOR.message_types_by_name['PodLabelSelector'] = _PODLABELSELECTOR
DESCRIPTOR.message_types_by_name['PodAffinityTerm'] = _PODAFFINITYTERM
DESCRIPTOR.message_types_by_name['WeightedPodAffinityTerm'] = _WEIGHTEDPODAFFINITYTERM
DESCRIPTOR.message_types_by_name['PodAffinity'] = _PODAFFINITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchLabels = _reflection.GeneratedProtocolMessageType('MatchLabels', (_message.Message,), {
  'DESCRIPTOR' : _MATCHLABELS,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.MatchLabels)
  })
_sym_db.RegisterMessage(MatchLabels)

LabelSelectorRequirement = _reflection.GeneratedProtocolMessageType('LabelSelectorRequirement', (_message.Message,), {
  'DESCRIPTOR' : _LABELSELECTORREQUIREMENT,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.LabelSelectorRequirement)
  })
_sym_db.RegisterMessage(LabelSelectorRequirement)

PodLabelSelector = _reflection.GeneratedProtocolMessageType('PodLabelSelector', (_message.Message,), {
  'DESCRIPTOR' : _PODLABELSELECTOR,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PodLabelSelector)
  })
_sym_db.RegisterMessage(PodLabelSelector)

PodAffinityTerm = _reflection.GeneratedProtocolMessageType('PodAffinityTerm', (_message.Message,), {
  'DESCRIPTOR' : _PODAFFINITYTERM,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PodAffinityTerm)
  })
_sym_db.RegisterMessage(PodAffinityTerm)

WeightedPodAffinityTerm = _reflection.GeneratedProtocolMessageType('WeightedPodAffinityTerm', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHTEDPODAFFINITYTERM,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.WeightedPodAffinityTerm)
  })
_sym_db.RegisterMessage(WeightedPodAffinityTerm)

PodAffinity = _reflection.GeneratedProtocolMessageType('PodAffinity', (_message.Message,), {
  'DESCRIPTOR' : _PODAFFINITY,
  '__module__' : 'pod_affinity_pb2'
  # @@protoc_insertion_point(class_scope:firmament.PodAffinity)
  })
_sym_db.RegisterMessage(PodAffinity)


# @@protoc_insertion_point(module_scope)
