# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_topology_node_desc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resource_desc_pb2 as resource__desc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resource_topology_node_desc.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!resource_topology_node_desc.proto\x12\tfirmament\x1a\x13resource_desc.proto\"\xa6\x01\n\x1eResourceTopologyNodeDescriptor\x12\x34\n\rresource_desc\x18\x01 \x01(\x0b\x32\x1d.firmament.ResourceDescriptor\x12;\n\x08\x63hildren\x18\x02 \x03(\x0b\x32).firmament.ResourceTopologyNodeDescriptor\x12\x11\n\tparent_id\x18\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[resource__desc__pb2.DESCRIPTOR,])




_RESOURCETOPOLOGYNODEDESCRIPTOR = _descriptor.Descriptor(
  name='ResourceTopologyNodeDescriptor',
  full_name='firmament.ResourceTopologyNodeDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_desc', full_name='firmament.ResourceTopologyNodeDescriptor.resource_desc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='firmament.ResourceTopologyNodeDescriptor.children', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='firmament.ResourceTopologyNodeDescriptor.parent_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=236,
)

_RESOURCETOPOLOGYNODEDESCRIPTOR.fields_by_name['resource_desc'].message_type = resource__desc__pb2._RESOURCEDESCRIPTOR
_RESOURCETOPOLOGYNODEDESCRIPTOR.fields_by_name['children'].message_type = _RESOURCETOPOLOGYNODEDESCRIPTOR
DESCRIPTOR.message_types_by_name['ResourceTopologyNodeDescriptor'] = _RESOURCETOPOLOGYNODEDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceTopologyNodeDescriptor = _reflection.GeneratedProtocolMessageType('ResourceTopologyNodeDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCETOPOLOGYNODEDESCRIPTOR,
  '__module__' : 'resource_topology_node_desc_pb2'
  # @@protoc_insertion_point(class_scope:firmament.ResourceTopologyNodeDescriptor)
  })
_sym_db.RegisterMessage(ResourceTopologyNodeDescriptor)


# @@protoc_insertion_point(module_scope)
