# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_stats.proto',
  package='firmament',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10task_stats.proto\x12\tfirmament\"\x96\x04\n\tTaskStats\x12\x0f\n\x07task_id\x18\x01 \x01(\x04\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x11\n\tcpu_limit\x18\x04 \x01(\x03\x12\x13\n\x0b\x63pu_request\x18\x05 \x01(\x03\x12\x11\n\tcpu_usage\x18\x06 \x01(\x03\x12\x11\n\tmem_limit\x18\x07 \x01(\x03\x12\x13\n\x0bmem_request\x18\x08 \x01(\x03\x12\x11\n\tmem_usage\x18\t \x01(\x03\x12\x0f\n\x07mem_rss\x18\n \x01(\x03\x12\x11\n\tmem_cache\x18\x0b \x01(\x03\x12\x17\n\x0fmem_working_set\x18\x0c \x01(\x03\x12\x17\n\x0fmem_page_faults\x18\r \x01(\x03\x12\x1c\n\x14mem_page_faults_rate\x18\x0e \x01(\x01\x12\x19\n\x11major_page_faults\x18\x0f \x01(\x03\x12\x1e\n\x16major_page_faults_rate\x18\x10 \x01(\x01\x12\x0e\n\x06net_rx\x18\x11 \x01(\x03\x12\x15\n\rnet_rx_errors\x18\x12 \x01(\x03\x12\x1a\n\x12net_rx_errors_rate\x18\x13 \x01(\x01\x12\x13\n\x0bnet_rx_rate\x18\x14 \x01(\x01\x12\x0e\n\x06net_tx\x18\x15 \x01(\x03\x12\x15\n\rnet_tx_errors\x18\x16 \x01(\x03\x12\x1a\n\x12net_tx_errors_rate\x18\x17 \x01(\x01\x12\x13\n\x0bnet_tx_rate\x18\x18 \x01(\x01\x62\x06proto3')
)




_TASKSTATS = _descriptor.Descriptor(
  name='TaskStats',
  full_name='firmament.TaskStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='firmament.TaskStats.task_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='firmament.TaskStats.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='firmament.TaskStats.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_limit', full_name='firmament.TaskStats.cpu_limit', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_request', full_name='firmament.TaskStats.cpu_request', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='firmament.TaskStats.cpu_usage', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_limit', full_name='firmament.TaskStats.mem_limit', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_request', full_name='firmament.TaskStats.mem_request', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_usage', full_name='firmament.TaskStats.mem_usage', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_rss', full_name='firmament.TaskStats.mem_rss', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_cache', full_name='firmament.TaskStats.mem_cache', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_working_set', full_name='firmament.TaskStats.mem_working_set', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_page_faults', full_name='firmament.TaskStats.mem_page_faults', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_page_faults_rate', full_name='firmament.TaskStats.mem_page_faults_rate', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='major_page_faults', full_name='firmament.TaskStats.major_page_faults', index=14,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='major_page_faults_rate', full_name='firmament.TaskStats.major_page_faults_rate', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_rx', full_name='firmament.TaskStats.net_rx', index=16,
      number=17, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_rx_errors', full_name='firmament.TaskStats.net_rx_errors', index=17,
      number=18, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_rx_errors_rate', full_name='firmament.TaskStats.net_rx_errors_rate', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_rx_rate', full_name='firmament.TaskStats.net_rx_rate', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_tx', full_name='firmament.TaskStats.net_tx', index=20,
      number=21, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_tx_errors', full_name='firmament.TaskStats.net_tx_errors', index=21,
      number=22, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_tx_errors_rate', full_name='firmament.TaskStats.net_tx_errors_rate', index=22,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_tx_rate', full_name='firmament.TaskStats.net_tx_rate', index=23,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=566,
)

DESCRIPTOR.message_types_by_name['TaskStats'] = _TASKSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskStats = _reflection.GeneratedProtocolMessageType('TaskStats', (_message.Message,), {
  'DESCRIPTOR' : _TASKSTATS,
  '__module__' : 'task_stats_pb2'
  # @@protoc_insertion_point(class_scope:firmament.TaskStats)
  })
_sym_db.RegisterMessage(TaskStats)


# @@protoc_insertion_point(module_scope)
